### ISSUE TITLE
Map pop-ups: coordinates not shown in 2 different circumstances

### ISSUE THREAD

**Issue by lucyfj** [legiongis/ead#3]
1. If two sites have the same coordinates, the location coordinates are not shown on the pop-up window on the map. 
In EAD this will happen quite frequently as we have split up big sites in the same location.

2. The coordinates are shown as 'not defined' on map on search results page

**Comment by lucyfj** [comment]
Here is an example of the clustered resources problem.
![clusteredresource_2](https://user-images.githubusercontent.com/16820044/30219382-2bc011be-94bc-11e7-84b7-b33f1a6fdb7f.PNG)
![clusteredresource_3](https://user-images.githubusercontent.com/16820044/30219383-2bc27288-94bc-11e7-9cee-709f269a4b9e.PNG)
![clusteredresource_4](https://user-images.githubusercontent.com/16820044/30219384-2bc5b182-94bc-11e7-8b0b-2086c7386a84.PNG)
![clusteredresource_5](https://user-images.githubusercontent.com/16820044/30219385-2bc6f31c-94bc-11e7-9269-7c6eedc85341.PNG)

**Comment by mradamcox** [comment]
Ok great, thanks for the screenshot, that illustrates the issue very
clearly.

**Comment by lucyfj** [comment]
Here are the screenshots for the 2nd problem; coordinates undefined in search results map:

The map view shows the coordinates correctly:
![coordsmappopup_1](https://user-images.githubusercontent.com/16820044/30636494-e6f8aef4-9df5-11e7-860d-eec263462341.PNG)

The search results page does not;
![searchcoordsmappopup_2](https://user-images.githubusercontent.com/16820044/30636522-0198d7c0-9df6-11e7-953e-f52ef2d5d6e8.PNG)

**Comment by mradamcox** [comment]
fixed while addressing #8

**Comment by lucyfj** [comment]
The first problem, map(main map screen) pop-up of clustered resources showing the location coordinates as 'undefined' is now fixed - thank you. 

But the problem of the coordinates not showing on the map pop-up on the map on the search screen is not fixed. Now the coordinates are not shown at all, whether they are clustered with another site or not. see the 2 examples.
![searchmap_popup_error](https://user-images.githubusercontent.com/16820044/33832962-a4448124-de86-11e7-9e45-7f173897c4b1.PNG)
![searchmap_popup_error2](https://user-images.githubusercontent.com/16820044/33832963-a46edd0c-de86-11e7-8607-f6691966ca03.PNG)

**Comment by mradamcox** [comment]
@lucyfj because this is working properly on the [demo ead search page](http://arches3.legiongis.com/ead/search?page=1&termFilter=%5B%5D&temporalFilter=%7B%22year_min_max%22%3A%5B%5D%2C%22filters%22%3A%5B%5D%2C%22inverted%22%3Afalse%7D&spatialFilter=%7B%22geometry%22%3A%7B%22type%22%3A%22%22%2C%22coordinates%22%3A%5B%5D%7D%2C%22buffer%22%3A%7B%22width%22%3A%220%22%2C%22unit%22%3A%22ft%22%7D%2C%22inverted%22%3Afalse%7D&mapExpanded=true&timeExpanded=false&no_filters=true&include_ids=false), I'm thinking that maybe you just need to "hard refresh" your browser to make sure it is using the new javascript files. Try holding control and hitting F5 to do so, and see if the problem persists.

**Comment by lucyfj** [comment]
Hi Adam,
Unfortunately, yesterday was my last full day in the office for some time. My brother and girlfriend are arriving from Texas for Christmas today and need showing around. Hopefully I will get some time to  further test this function from home.

Thank you very much for the help in getting the sever going again. It seems that we have permission issues and a firewall on our server and so it ends up being a little more complicated but I finally got it going. One thing, the elastic search is running in the old directory, opt/projects/ead/ead while Arches is running in the new directory opt/arches/ead/ead Could this cause any problems?

**Comment by lucyfj** [comment]
Yes, the problem is fixed, thank you. Clearly the new javascript files hadn't kicked in before.
